Remove unused include file
xmos/lib_logging pull request #22
Opened 2019-08-29 13:14 UTC by mbruno-xmos

This removes the two #include <print.h> lines in debug_printf.c.

This was causing a conflict with a project that had its own print.h
header file, and nothing in print.h is used anyway.

2020-11-25 11:31 UTC, mbanth requested changes
Looks like a substantial and beneficial enhancement to logging functionality.  It deserves further review.  A copyright date range has become stale.  Otherwise I did not identify any changes needed during my very cursory review.

2020-11-25 11:31 UTC, mbanth commented on lib_logging/src/debug_printf.c
> +// Copyright (c) 2014-2019, XMOS Ltd, All rights reserved
Copyright date range needs updated to 2014-2020.

2026-01-12 14:15 UTC, xalbertoisorna commented
@mbanth this can be partially closed by #87 
For the remaining functionality, I created: [LSM-219](https://xmosjira.atlassian.net/browse/LSM-219?atlOrigin=eyJpIjoiOTUzZTA4MTMzYjM1NGE0Y2FkNmIyZTkzNjM3MzA1MmEiLCJwIjoiaiJ9)

[LSM-219]: https://xmosjira.atlassian.net/browse/LSM-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2026-01-12 14:20 UTC, mbanth commented
I'm closing this PR as suggested by @xalbertoisorna.  PR #87 has removed the dependency on the print.h header.  The addition of two more print functions has been captured in Jira issue [LSM-219](https://xmosjira.atlassian.net/browse/LSM-219?atlOrigin=eyJpIjoiOTUzZTA4MTMzYjM1NGE0Y2FkNmIyZTkzNjM3MzA1MmEiLCJwIjoiaiJ9).

[LSM-219]: https://xmosjira.atlassian.net/browse/LSM-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2026-01-12 14:20 UTC, closed without merging